version: '3.9'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./containers/nginx/certs:/etc/nginx/ssl:ro
      - ./containers/nginx/access.log:/etc/nginx/access_log.log
      - ./containers/nginx/error.log:/etc/nginx/error_log.log
      - ./containers/nginx/cache/:/etc/nginx/cache
    depends_on:
      - nextjs
      - nodejs
    ports:
      - 80:80
      - 443:443

  nextjs:
    build: .
    container_name: nextjs
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - /app/.next
    expose:
      - '3000'
    env_file:
      - .env.local
    depends_on:
      - mongo

  nodejs:
    build: ./containers/nodejs
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - ./containers/nodejs/node_modules:/app/node_modules
    expose:
      - '3001'
      - '3002'
    env_file:
      - .env.local
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - db:/data/db
    env_file:
      - .env.local
    expose:
      - '27017'
    ports:
      - 7017:27017

volumes:
  db:
